version: '3.8'
services:
    frontend:
        networks:
            - react-express
        ports:
            - 3000:3000
        build: ./frontend
    backend:
        networks:
            - react-express
            - express-mongo
        build: ./backend
    mongo:
        networks:
            - express-mongo
        image: mongo
        volumes:
            - ./data:/data/db
networks:
    react-express:
        external: true
    express-mongo:
        external: true
